jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Build with Maven, Deploy snapshot to maven central
      run: "mvn --no-transfer-progress -B verify --file pom.xml\nexport MY_POM_VERSION=`mvn\
        \ -q -Dexec.executable=\"echo\" -Dexec.args='${projects.version}' --non-recursive\
        \ org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`\necho \"POM VERSION\" ${MY_POM_VERSION}\n\
        if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];\nthen\n    mvn --no-transfer-progress\
        \ -B clean deploy\nelse\n    echo \"not deploying release: \" ${MY_POM_VERSION}\n\
        fi\n"
    strategy:
      matrix:
        java:
        - 8
name: Build Test Deploy v1
on:
  repository_dispatch:
    types: trigger-ga___maven-v1.yml
