jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B verify --file pom.xml
    strategy:
      matrix:
        java:
        - 8
name: Build Test PR v1
on:
  repository_dispatch:
    types: trigger-ga___maven-v1-pulls.yml
