jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Build with Maven, Deploy snapshot to maven central
      run: "export MY_POM_VERSION=`mvn -q -Dexec.executable=\"echo\" -Dexec.args='${projects.version}'\
        \ --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`\necho \"\
        POM VERSION\" ${MY_POM_VERSION}\nif [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];\n\
        then\n  mvn --no-transfer-progress -B install --file pom.xml\n  export MY_JAVA_VERSION=`java\
        \ -version 2>&1 | head -1 | cut -d'\"' -f2 | sed '/^1\\./s///' | cut -d'.'\
        \ -f1`\n  echo \"JAVA VERSION\" ${MY_JAVA_VERSION}\n  if [[ ${MY_JAVA_VERSION}\
        \ == \"11\" ]];\n  then\n    export MY_POM_VERSION=`mvn -q -Dexec.executable=\"\
        echo\" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`\n\
        \    echo \"POM VERSION\" ${MY_POM_VERSION}\n    mvn --no-transfer-progress\
        \ -B clean deploy\n  else\n    echo \"not deploying on java version: \" ${MY_JAVA_VERSION}\n\
        \  fi\nelse\n  echo \"not building and maven publishing project as it is a\
        \ release version: \" ${MY_JAVA_VERSION}\nfi\n"
    strategy:
      matrix:
        java:
        - 11
        - 14
        - 17
name: Build Test Deploy master
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
