jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      SC_NEXT_VERSION: null
      SC_VERSION: null
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: generate-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      id: prepare-release
      name: Run prepare release script
      run: "export MY_POM_VERSION=`mvn -q -Dexec.executable=\"echo\" -Dexec.args='${projects.version}'\
        \ --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`\nif [[ $MY_POM_VERSION\
        \ =~ ^.*SNAPSHOT$ ]];\nthen\n  . ./CI/prepare-release-v1.sh\n  echo \"PREPARE_RELEASE_OK=yes\"\
        \ >> $GITHUB_ENV\nelse\n  echo \"not preparing release for release version:\
        \ \" ${MY_POM_VERSION}\n  echo \"PREPARE_RELEASE_OK=no\" >> $GITHUB_ENV\n\
        fi\necho \"SC_VERSION=$SC_VERSION\" >> $GITHUB_ENV\necho \"SC_NEXT_VERSION=$SC_NEXT_VERSION\"\
        \ >> $GITHUB_ENV\n"
    - continue-on-error: true
      if: env.PREPARE_RELEASE_OK == 'yes'
      name: Create Prepare Release Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: prepare-release-${{ env.SC_VERSION }}
        commit-message: prepare release ${{ env.SC_VERSION }}
        title: prepare release ${{ env.SC_VERSION }}
        token: ${{ steps.generate-token.outputs.token }}
name: Prepare Release V1
on:
  repository_dispatch:
    types: trigger-ga___prepare-release-v1.yml
